image:
  repository: ghcr.io/23technologies/gardener-extension-os-k3os
  tag: latest
  pullPolicy: IfNotPresent

resources: {}

vpa:
  enabled: true
  resourcePolicy:
    minAllowed:
      cpu: 50m
      memory: 64Mi
  updatePolicy:
    updateMode: "Auto"

controllers:
  concurrentSyncs: 5
  ignoreOperationAnnotation: false

disableControllers: []
